### ISSUE TITLE
Clarify where future core discussions should occur

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/governance#22]
Since GitHub removed Team discussions, where should we have discussions now?

**Comment by rhendric** [comment]
https://github.com/purescript/core-team-discussions/discussions
https://github.com/purescript/infra-team-discussions/discussions
https://github.com/purescript/compiler-team-discussions/discussions

I guess we should add these links to the readme or something? They aren't that discoverable.

**Comment by JordanMartinez** [comment]
Ah, ok. I was so used to using Issues, that when I saw those repos didn't have them, I wasn't sure how we were supposed to use them. Let me add those.
